"""
Database persistence tests for the SmartFit VirtualFitting model.

This module verifies that a VirtualFitting record can be:

1. Created and inserted into PostgreSQL.
2. Retrieved from the database.
3. Deleted after the test completes.

The test uses a temporary record so that it does not leave
unnecessary test data in the development database.
"""

import uuid

from app.db.database import SessionLocal
from app.models import VirtualFitting


def test_create_and_retrieve_virtual_fitting():
    """
    Verify that a VirtualFitting record can be created and retrieved
    from PostgreSQL.

    This test confirms that SQLAlchemy can successfully perform
    the basic database operations required to persist a virtual
    fitting result in the SmartFit database.
    """

    # Create a new SQLAlchemy database session.
    db = SessionLocal()

    # Generate temporary UUIDs to represent the user, garment,
    # and avatar associated with this test fitting.
    #
    # These relationships will be refined later when the complete
    # database relationship strategy is finalized.
    test_user_id = uuid.uuid4()
    test_garment_id = uuid.uuid4()
    test_avatar_id = uuid.uuid4()

    try:
        # Create a temporary VirtualFitting object.
        #
        # The values represent an example result that could be
        # generated by the SmartFit virtual fitting process.
        test_fitting = VirtualFitting(
            user_id=test_user_id,
            garment_id=test_garment_id,
            avatar_id=test_avatar_id,
            recommended_size="Medium",
            fit_result="Good Fit",
        )

        # Add the VirtualFitting object to the current
        # database session.
        db.add(test_fitting)

        # Commit the transaction so that the VirtualFitting record
        # is written to the PostgreSQL database.
        db.commit()

        # Refresh the object so that SQLAlchemy retrieves
        # database-generated values such as the fitting UUID
        # and creation timestamp.
        db.refresh(test_fitting)

        # Confirm that PostgreSQL generated a UUID for the
        # virtual fitting record.
        assert test_fitting.fitting_id is not None

        # Retrieve the VirtualFitting record from PostgreSQL
        # using the generated fitting UUID.
        retrieved_fitting = db.query(VirtualFitting).filter(
            VirtualFitting.fitting_id == test_fitting.fitting_id
        ).first()

        # Confirm that the VirtualFitting record was successfully
        # retrieved.
        assert retrieved_fitting is not None

        # Verify that the retrieved user ID matches the ID used
        # to create the test fitting.
        assert retrieved_fitting.user_id == test_user_id

        # Verify that the retrieved garment ID matches the ID used
        # to create the test fitting.
        assert retrieved_fitting.garment_id == test_garment_id

        # Verify that the retrieved avatar ID matches the ID used
        # to create the test fitting.
        assert retrieved_fitting.avatar_id == test_avatar_id

        # Verify that the recommended clothing size was correctly
        # stored and retrieved.
        assert retrieved_fitting.recommended_size == "Medium"

        # Verify that the fitting result was correctly stored
        # and retrieved.
        assert retrieved_fitting.fit_result == "Good Fit"

        # Confirm that the creation timestamp was automatically
        # generated when the VirtualFitting record was created.
        assert retrieved_fitting.created_at is not None

    finally:
        # Remove the temporary test record from the database.
        #
        # This ensures that running the test does not leave
        # unnecessary test data in the SmartFit database.
        if (
            "test_fitting" in locals()
            and test_fitting.fitting_id is not None
        ):
            db.delete(test_fitting)
            db.commit()

        # Close the database session.
        db.close()