@startuml Data_Layer

title Data Layer of the Proposed Virtual Fitting System

top to bottom direction

skinparam componentStyle rectangle
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype ortho
skinparam defaultTextAlignment center
skinparam ArrowThickness 1.5

skinparam packageBorderColor Black
skinparam packageBackgroundColor White

skinparam componentBorderColor Black
skinparam componentBackgroundColor White

skinparam databaseBorderColor Black
skinparam databaseBackgroundColor White

skinparam noteBorderColor Black
skinparam noteBackgroundColor White

skinparam nodesep 50
skinparam ranksep 60

'========================
' Application Layer
'========================

package "Application Layer" {

    component "FastAPI Backend\n(Business Logic & API Services)" as Backend

}

'========================
' Data Layer
'========================

package "Data Layer" {

    database "PostgreSQL Database" as DB

}

'========================
' Data Flow
'========================

Backend --> DB

'========================
' Stored Data
'========================

note bottom of DB
    Stored Data
    -------------------------
    Users
    Garments
    Body Measurements
    Avatars
    Virtual Fitting Results
end note

@enduml